name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: |
          flutter pub get
          flutter channel master
          flutter upgrade
          flutter config --enable-web
          flutter build web
      - name: Firebase GitHub Action
        uses: pizzafox/firebase-action@1.0.7
        env:
          PROJECT_ID: "flappy-8f0a3"
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
          args: deploy  
